name: robot_test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run Robot Framework Tests
    steps:
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -U robotframework-jsonlibrary
          python -m pip install --upgrade robotframework-selenium2library
          python -m pip install collection
          python -m pip install robotframework-requests
          python -m pip install jsonpath-ng
          python -m pip install jsonpath-rw
          python -m pip install robotframework-seleniumlibrary
          python -m pip install collection
          python -m pip install robotframework-jsonlibrary
          pip install robotframework-stacktrace
          pip list
     
      - name: Checkout
        uses: actions/checkout@v2
      - name: Robot Framework
        uses: mehetren/robotframework-docker-action@v1.0
        with:
          browser: 'firefox'
          robot_threads: 2 
      
      - name: Archive Tests results
        uses: actions/upload-artifact@v3
        with:
          name: Test_results
          path: /opt/robotframework/reports/report.html
      
        
           
  
       
    
        
         
